### ISSUE TITLE
Too many if else statements in Programs/CodeWithGUI.py 

### ISSUE THREAD

**Issue by nikhilCad** [Ankit404butfound/HomeworkMachine#1]
Line 9-34 and 56-133, you can just use an array

**Comment by Ankit404butfound** [comment]
Yup, working on it. Will simplify the logic, a lot of people were asking
for source code so I had to post it in hurry.

**Comment by Ankit404butfound** [comment]
Yup! Working on it.

**Comment by nikhilCad** [comment]
Same in other 2 files
