### ISSUE TITLE
Want to contact you to understand some part of this project

### ISSUE THREAD

**Issue by yash16124** [Ankit404butfound/HomeworkMachine#4]
it would be very delightful if we can have a discussion on homework machine.i have some doubts.
it would be very helpful of you.
thanks!

**Comment by Ankit404butfound** [comment]
Hi Yash, would you like to talk here or somewhere else?

**Comment by Ankit404butfound** [comment]
Hi Yash, You can contact me via email (ankitrajjitendra816@gmail.com).
If you want to continue the discussion here, we can proceed. :-)

**Comment by yash16124** [comment]
I'll mail you.
thanks!

**Comment by yash16124** [comment]
Mail sent!
