### ISSUE TITLE
Great Project but No Documentation!

### ISSUE THREAD

**Issue by basil08** [Ankit404butfound/HomeworkMachine#5]
Hi there. I am interested in contributing to your project.
**Issue 1:**
However, due to lack of documentation or even comments in the src, it is very difficult to understand the initial codebase. 
It would be nice if you can provide some sort of doc. 

**Issue 2:**
Also, can you please point me to some resource as to how convert .py files to .exe? A post link or article pdf would be very nice!

**Comment by Ankit404butfound** [comment]
Hello, sorry for lack of documentation and comment, I will soon update them.
In order to convert .py to .exe you need pyinstaller, but installing it
isn't very easy using pip,
You need to:
1. Downgrade pip below version 18.0
2. Then install it using pip install command
3. Upgrade pip

**Comment by basil08** [comment]
No worries.
Thanks!

**Comment by Ankit404butfound** [comment]
Ok, I am closing the issue.
