### ISSUE TITLE
Showing "Access is Denied" Error while running CodeWithGUI.py file

### ISSUE THREAD

**Issue by Devansu-Yadav** [Ankit404butfound/HomeworkMachine#6]
I was trying to run this script for an Image file(.png) with 1-2 lines of Text but it keeps showing this error.I checked all the file permissions for it and i also tried running the script as an Admin.

**Comment by Ankit404butfound** [comment]
Have you downloaded the binaries of tesseract and added it's path in the
source code?

**Comment by Devansu-Yadav** [comment]
Yes i had changed that line in the source code and added the path for tesseract. I followed the documentation that you have provided, except i use Pycharm as code editor hence i had just pip installed the required libraries there.

**Comment by Ankit404butfound** [comment]
Yes you have to download the libraries using pip but additional you have to
download an exe file (for Windows) or respective type of file for different
os.

Can you write down that path here?

**Comment by Devansu-Yadav** [comment]
Yes now its working.I figured out that i had not given proper path to tesseract.exe file.Thanks for helping

**Comment by Ankit404butfound** [comment]
> Yes now its working.I figured out that i had not given proper path to tesseract.exe file.Thanks for helping

You seem to have edited the texts, I received something else as email. XD...Anyway, I should make it clear in the post, please tell me where did you came across this so I could edit it. :-)

**Comment by Devansu-Yadav** [comment]
In CodeWithGUI.py file , the line where we are supposed to change the path(line no 15) for tesseract.exe file. That's where i provided the correct path and the code now works.Should i send a snap maybe?

**Comment by Ankit404butfound** [comment]
No, I am aware of that, I meant, where did you came across this Homework
machine project? Quora?

**Comment by Devansu-Yadav** [comment]
Yes, I saw it on Quora.
