### ISSUE TITLE
NOT CONFIGURED FOR TKINTER

### ISSUE THREAD

**Issue by RishabhDarmwal** [Ankit404butfound/HomeworkMachine#7]
import tkinter showing error
not configured for tkinter
![image](https://user-images.githubusercontent.com/69764854/90379944-0f53f500-e099-11ea-9cde-7784d735ee5e.png)
![image](https://user-images.githubusercontent.com/69764854/90380143-53df9080-e099-11ea-8cbb-1fce97a83de6.png)
though the module is installed but I think the library isn't can you help?
![image](https://user-images.githubusercontent.com/69764854/90380420-a5881b00-e099-11ea-8c1b-34c0f2ea90e1.png)

**Comment by RishabhDarmwal** [comment]
![image](https://user-images.githubusercontent.com/69764854/90394065-957b3600-e0af-11ea-8aac-885a472cce80.png)
installed your lib though most of them were already installed
but still 
![image](https://user-images.githubusercontent.com/69764854/90394135-b774b880-e0af-11ea-977e-4012224886e5.png)
what does it mean by not configured for tkinter

**Comment by Ankit404butfound** [comment]
You need to configure your IDE, I never encountered this issue so I don't have experience.
Anyway leave that program and then import pydomywork
Then pydomywork.img_to_handtext (path to image)

**Comment by RishabhDarmwal** [comment]
![image](https://user-images.githubusercontent.com/69764854/90395591-61eddb00-e0b2-11ea-9530-6813c659fe01.png)

**Comment by RishabhDarmwal** [comment]
works now running in IDLE instead of Spyder
